version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - 8001:80
    environment:
      - NGINX_HOST=cards.localhost
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./logs/nginx/:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl

  php:
    build: docker/php-fpm
    ports:
      - 9000
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d